# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      python -m pip install --upgrade pip
      python -m pip install biopython
      python -m pip install pandas
      python -m pip install numpy
      python -m pip install xlrd
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
